In [ ]:
# open source python library
# allows for creation of multi-dimensional arrays and matrix
# perform statistical and mathematical operations
# wide number of functions for data based operations

In [5]:
import numpy as np

arrays=np.array([[1,2,3],[4,5,6]])
type(arrays)
print(arrays)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

ints=np.array([[1,2,3],[4,5,6],[7,8,9]])
ints

floats=np.array([[0.0,0.1,0.2],[0.3,0.4,0.5,0.6,0.7]])

floats

array([list([0.0, 0.1, 0.2]), list([0.3, 0.4, 0.5, 0.6, 0.7])],
      dtype=object)

In [9]:
# show the number of dimensions of a given array
ints.ndim
floats.ndim

1

In [11]:
# display shape of given array (row, column) format
ints.shape
floats.shape

(2,)

In [13]:
#dispaly size of given array
ints.size
floats.size

2

In [14]:
for i in ints:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [16]:
# create 1-D array
for i in ints.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [17]:
# generate array
np.zeros(3)

array([0., 0., 0.])

In [19]:
# generate array in specific matrix and given specific data type
# (rowSize, columnSize)
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
# create spefic RxC matrix with specific value
np.full((3,3),69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [24]:
# print values from spefici range
# (upper, lower, steps(+ve or -ve))
np.arange(5)
np.arange(2,10)
np.arange(20,0,-5)

array([20, 15, 10,  5])

In [25]:
# evenly spaced float point ranges
# (startValue, endValue)
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
# generate equally spaced float array within given num value
np.linspace(1,25,num=5)

array([ 1.,  7., 13., 19., 25.])

In [31]:
# convert 1-D array into multi-dimensional array
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [32]:
# generate a random array
# return different array for every execution
np.random.randint(1,15,5)

array([13,  6,  4, 11, 14])

In [39]:
# sum each array element
# (startValue, endValue, elements in array)
radom=np.random.randint(1,10,5)
radom
radom.sum()

26

In [43]:
# min, max, mean and sd of array elements
radom.min()
radom.max()
radom.mean()
radom.std()

2.3151673805580453

In [49]:
nps=np.arange(1,10,2)
nps1=np.random.randint(1,20,5)

nps+nps1
nps*nps1
nps/3
nps1/2
np.sqrt(nps)
np.sqrt(nps1)

array([1.73205081, 4.12310563, 2.82842712, 2.64575131, 2.44948974])

# functions

In [62]:
arr=np.random.randint(1,500,15)
arr

arr1=arr.reshape(3,5)
arr1

index_val=np.argpartition(arr, -5)[-5:]
index_val
np.sort(arr[index_val])

index_val1=np.argpartition(arr1,-3,axis=0)[-5:]
index_val1

np.sort(arr1[index_val1])

array([[[ 56,  63,  78, 225, 325],
        [ 56,  63,  78, 225, 325],
        [ 56,  63,  78, 225, 325],
        [156, 231, 296, 404, 448],
        [ 83, 149, 152, 223, 466]],

       [[156, 231, 296, 404, 448],
        [156, 231, 296, 404, 448],
        [156, 231, 296, 404, 448],
        [ 56,  63,  78, 225, 325],
        [ 56,  63,  78, 225, 325]],

       [[ 83, 149, 152, 223, 466],
        [ 83, 149, 152, 223, 466],
        [ 83, 149, 152, 223, 466],
        [ 83, 149, 152, 223, 466],
        [156, 231, 296, 404, 448]]])

In [63]:
# flatten an array
index_val2=np.argpartition(arr1.ravel(),-5)[-5:]
index_val2

# unflatten an array


array([ 0, 11,  1,  8,  4])

In [64]:
index_val3=np.unravel_index(index_val2, arr1.shape)
arr1[index_val3]

array([296, 466, 404, 325, 448])

In [66]:
# match 2 arrays and return boolean value
np.allclose(arr,arr1.ravel(),0.1)

True

In [79]:
arr

array([296, 404, 231, 156, 448,  56,  63,  78, 325, 225,  83, 466, 149,
       223, 152])

In [77]:
np.clip(arr,100,250)
arr

array([296, 404, 231, 156, 448,  56,  63,  78, 325, 225,  83, 466, 149,
       223, 152])

# indexing and slicing

In [80]:
arrays1=np.random.randint(1,30,10)
arrays1

array([15,  1, 10,  5, 23, 16, 21, 21, 20, 28])

In [86]:
arrays1[5]
arrays1[2:5]
arrays1[:4]
arrays1[:-1]

array([15,  1, 10,  5, 23, 16, 21, 21, 20])

In [88]:
arrays2=np.arange(1,10)
arrays2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arrays2[:2]=69
arrays2

array([69, 69,  3,  4,  5,  6,  7,  8,  9])

In [91]:
arrays3=np.random.randint(1,50,15)
arrays3=arrays3.reshape(3,5)
arrays3

array([[28,  5, 18,  1, 15],
       [26, 11, 25,  9, 48],
       [30, 19, 33, 44,  3]])

In [95]:
arrays3[2]

array([30, 19, 33, 44,  3])

In [103]:
arrays3[2][1]
arrays3[:2]
arrays3[:,1:4]
arrays3[:,(1,4)]

array([[ 5, 15],
       [11, 48],
       [19,  3]])

In [115]:
arrays4=np.arange(1,10)

# bounded array; modification of one lead to modification of other
arrays4_c=arrays4.view()
arrays4_c

arrays4[2]*=3
arrays4
arrays4_c

arrays4_c[3]+=10
arrays4_c

# only copied array is affcted
arrays4c=arrays4.copy()
arrays4c

arrays4c[0]-=5
arrays4c
arrays4

array([ 1,  2,  9, 14,  5,  6,  7,  8,  9])